# Generated by Django 5.0.3 on 2024-03-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, unique=True, verbose_name='Заголовок')),
                ('date', models.CharField(verbose_name='Дата публикации')),
                ('author_name', models.CharField(verbose_name='Имя автора')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('author_link', models.CharField(verbose_name='Ссылка на автора')),
                ('article_link', models.CharField(db_index=True, unique=True, verbose_name='Ссылка на статью')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='hubs.hub', verbose_name='Идентификатор хаба')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
    ]
